//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisedCar
    {
        public AdvertisedCar()
        {
            this.Owners_Cars_Ref = new HashSet<Owners_Cars_Ref>();
        }
    
        public int ID { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string AdvertisedPriceType { get; set; }
        public Nullable<decimal> ECGAmount { get; set; }
        public Nullable<decimal> DAPAmount { get; set; }
        public Nullable<decimal> AdvertisedAmount { get; set; }
    
        public virtual ICollection<Owners_Cars_Ref> Owners_Cars_Ref { get; set; }
    }
}
