//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.Owners_Cars_Ref = new HashSet<Owners_Cars_Ref>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string DealerABN { get; set; }
        public string OwnerType { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Owners_Cars_Ref> Owners_Cars_Ref { get; set; }
    }
}
