//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owners_Cars_Ref
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public int CarId { get; set; }
    
        public virtual AdvertisedCar AdvertisedCar { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
